application: htmlhyphenator
version: 1
runtime: python
api_version: 1

handlers:
# Static files

- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: app.py

